language: objective-c
rvm: 1.9.3
before_install: gem install cocoapods xcpretty --no-ri --no-rdoc
before_script:
  - export LANG=en_US.UTF-8
  - cd Demo; pod install
script:
  - set -o pipefail && xcodebuild -workspace OAuthIOExample.xcworkspace -scheme OAuthIOExample -configuration Debug -sdk iphonesimulator clean build | xcpretty -c